name: Sample Helloworld application CI
on:
  workflow_dispatch:
    inputs:
       brnach:
          description: brnach name
          required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello from Githubactions pipelines

